// Reach — content data. Grow the app by adding to these arrays.
// kind: 'yoga' | 'calisthenics'
// tags: 'toe-touch' | 'pull-up' | 'mobility' | 'strength' | 'recovery'

const MOVES = [
  // ——— Yoga / floor ———
  { id: 'childs_pose', name: "Child's Pose", kind: 'yoga', tags: ['recovery', 'mobility'],
    text: "Knees wide, big toes touching, hips settling back toward the heels. Walk the hands forward and let the forehead rest on the mat. Breathe into the back of the ribs.",
    cue: "Nothing to achieve here — just let the floor hold you." },
  { id: 'cat_cow', name: 'Cat / Cow', kind: 'yoga', tags: ['mobility'],
    text: "On hands and knees, wrists under shoulders, knees under hips. Inhale to drop the belly and lift the chest; exhale to round the spine and tuck the chin. Move one vertebra at a time.",
    cue: "Let the breath lead the spine, not the other way around." },
  { id: 'tabletop_ext', name: 'Tabletop Arm & Leg Extensions', kind: 'yoga', tags: ['mobility', 'strength'],
    text: "From hands and knees, reach the right arm forward and the left leg back until both are level with the torso. Hold a breath, then switch. Keep the hips square to the floor.",
    cue: "Long, not high — reach out through the fingers and the heel." },
  { id: 'low_lunge_opener', name: 'Low Lunge Hip Opener', kind: 'yoga', tags: ['mobility', 'toe-touch'],
    text: "Step one foot between the hands, back knee down. Sink the hips forward and down until you feel the front of the back thigh open. Hands on the mat or on the front thigh.",
    cue: "Tuck the tailbone slightly — the stretch moves from the low back into the hip." },
  { id: 'down_dog', name: 'Downward Dog', kind: 'yoga', tags: ['mobility', 'toe-touch'],
    text: "Hands shoulder-width, feet hip-width, hips lifted back and up. Press the floor away and let the spine lengthen. Bend the knees generously so the back stays long.",
    cue: "Heels are a destination, not a requirement." },
  { id: 'walk_up', name: 'Walk Feet to Hands', kind: 'yoga', tags: ['mobility'],
    text: "From Downward Dog, step or walk the feet forward to meet the hands. Let the head hang heavy at the top." },
  { id: 'halfway_lift', name: 'Halfway Lift', kind: 'yoga', tags: ['mobility'],
    text: "From a forward fold, hands to the shins and lengthen the spine until the back is flat and the chest points forward. Shoulders slide down the back.",
    cue: "Flat back over straight legs — bend the knees to get there." },
  { id: 'forward_fold', name: 'Standing Forward Fold', kind: 'yoga', tags: ['toe-touch', 'mobility'],
    text: "Feet hip-width, hinge from the hips and fold. Let the arms and head hang. Soften the knees until the hamstrings release, then slowly straighten as far as is comfortable.",
    cue: "This is the daily toe-touch rep. Time under tension does the work." },
  { id: 'mountain', name: 'Mountain', kind: 'yoga', tags: ['mobility'],
    text: "Stand tall, feet grounded, arms at the sides or overhead. Crown lifts, shoulders soften, breath even." },
  { id: 'plank', name: 'Plank', kind: 'yoga', tags: ['strength'],
    text: "Shoulders over wrists, heels pressing back, one long line from crown to heels. Ribs knit in, glutes on.",
    cue: "Push the floor away — don't sag between the shoulder blades.",
    swap: "Too much? Drop the knees and keep the line from crown to knees." },
  { id: 'chaturanga', name: 'Plank Shift-Forward Lower', kind: 'yoga', tags: ['strength'],
    text: "From plank, shift forward on the toes until the shoulders pass the wrists, then bend the elbows straight back and lower with control, hugging the elbows in.",
    cue: "Elbows brush the ribs. Lower knees first if the chest drops faster than the hips." },
  { id: 'cobra', name: 'Cobra', kind: 'yoga', tags: ['mobility'],
    text: "Lying on the front, hands under the shoulders, press lightly and lift the chest. Elbows stay bent and close to the body; legs stay heavy.",
    cue: "Lead with the sternum, not the chin." },
  { id: 'runners_lunge', name: "Runner's Lunge", kind: 'yoga', tags: ['mobility', 'toe-touch'],
    text: "Front foot between the hands, back leg long and strong, hips low. Fingertips or forearms toward the mat on the inside of the front foot." },
  { id: 'half_splits', name: 'Half Splits', kind: 'yoga', tags: ['toe-touch', 'mobility'],
    text: "From a low lunge, shift the hips back over the back knee and straighten the front leg, flexing that foot. Fold gently over the front thigh.",
    cue: "Square the hips first, then fold. Depth is not the point." },
  { id: 'knee_to_nose', name: 'Knee-to-Nose', kind: 'yoga', tags: ['strength', 'mobility'],
    text: "From Downward Dog, lift one leg, then round the spine and draw that knee toward the nose. Hold, then send it back long." },
  { id: 'warrior2', name: 'Warrior 2', kind: 'yoga', tags: ['strength', 'mobility'],
    text: "Front knee bent over the ankle, back foot parallel to the mat's back edge, arms reaching front and back at shoulder height. Gaze past the front fingertips.",
    cue: "Most enter on an inhale — exhale, settle in." },
  { id: 'side_angle', name: 'Extended Side Angle', kind: 'yoga', tags: ['mobility'],
    text: "From Warrior 2, set the front forearm on the front thigh (or fingertips to the floor) and sweep the top arm over the ear. Chest rotates open toward the ceiling." },
  { id: 'reverse_warrior', name: 'Reverse Warrior', kind: 'yoga', tags: ['mobility'],
    text: "From Warrior 2, turn the front palm up and reach it overhead as the back hand slides down the back leg. Keep the front knee bent.",
    cue: "Lengthen the side body before you lean." },
  { id: 'triangle', name: 'Triangle', kind: 'yoga', tags: ['toe-touch', 'mobility'],
    text: "Straighten the front leg, reach forward, then set the bottom hand on the shin or a block and open the top arm to the sky. Both sides of the waist stay long." },
  { id: 'reverse_triangle', name: 'Reverse Triangle', kind: 'yoga', tags: ['mobility', 'toe-touch'],
    text: "Square the hips forward over a straight front leg, set the opposite hand outside the front foot, and twist open through the chest.",
    cue: "Shorten your stance before you deepen the twist." },
  { id: 'star', name: 'Five-Pointed Star', kind: 'yoga', tags: ['mobility'],
    text: "Feet wide, legs straight, arms wide at shoulder height. Stand broad and breathe — five long points reaching out from the centre." },
  { id: 'wide_leg_fold', name: 'Wide-Leg Forward Fold', kind: 'yoga', tags: ['toe-touch'],
    text: "Feet wide and parallel, hinge at the hips and fold. Hands to the floor, ankles, or clasped behind the back. Let the crown drop." },
  { id: 'standing_split', name: 'Standing Split', kind: 'yoga', tags: ['toe-touch', 'strength'],
    text: "From a forward fold, lift one leg behind you. Hands frame or hold the standing ankle; the lifted leg reaches back before it reaches up.",
    cue: "Four corners of the foot, hips level, buoyant through the knee — let your crown fall off." },
  { id: 'knee_raise', name: 'Standing Knee Raise', kind: 'yoga', tags: ['strength', 'mobility'],
    text: "From standing split, draw the lifted knee in toward the chest and stand up tall. Balance, breathe, and find the standing foot again." },
  { id: 'figure4_standing', name: 'Standing Figure 4', kind: 'yoga', tags: ['mobility'],
    text: "Cross one ankle above the opposite knee and sit the hips back like a one-legged chair. Chest stays lifted, standing knee tracks over the toes.",
    swap: "Wobbly? Fingertips to a wall or chair back." },
  { id: 'warrior3', name: 'Warrior 3', kind: 'yoga', tags: ['strength'],
    text: "Hinge forward from figure 4 or a lunge until the torso and back leg form one line parallel to the floor. Hips level, back toes point down." },
  { id: 'neck_rolls', name: 'Neck Rolls', kind: 'yoga', tags: ['mobility', 'recovery'],
    text: "Drop the right ear toward the right shoulder, then roll the chin slowly across the chest to the left. Half circles only — avoid rolling back.",
    cue: "Slow enough that you could stop anywhere." },
  { id: 'thread_needle', name: 'Thread the Needle', kind: 'yoga', tags: ['mobility'],
    text: "From hands and knees, slide the right arm under the left, shoulder and temple to the mat. Left hand presses to deepen the twist. Hips stay high." },
  { id: 'low_lunge_reach', name: 'Low Lunge with Overhead Reach', kind: 'yoga', tags: ['mobility'],
    text: "Low lunge, back knee down, both arms sweep overhead. Lift the chest and reach up and slightly back through the fingertips." },
  { id: 'standing_side_bend', name: 'Standing Side Bend', kind: 'yoga', tags: ['mobility'],
    text: "Feet grounded, reach both arms up, catch one wrist and lean gently to the side. Keep both feet evenly weighted; breathe into the open ribs." },
  { id: 'ragdoll', name: 'Ragdoll Fold', kind: 'yoga', tags: ['toe-touch', 'recovery'],
    text: "Feet hip-width, knees softly bent, fold and take hold of opposite elbows. Sway a little side to side and let the head be heavy." },
  { id: 'lizard', name: 'Lizard', kind: 'yoga', tags: ['mobility', 'toe-touch'],
    text: "Front foot outside the same-side hand, back knee down or lifted. Walk the front foot wider and lower onto forearms or blocks if available.",
    swap: "No blocks? Stack two books or stay on the hands." },
  { id: 'pyramid', name: 'Pyramid', kind: 'yoga', tags: ['toe-touch'],
    text: "Short stance, both legs straight, hips square, fold over the front leg with a long spine. Front foot forward, back foot at 45 degrees.",
    cue: "Hamstring stretch lives in the length of the spine, not the depth of the fold." },
  { id: 'seated_fold', name: 'Seated Forward Fold', kind: 'yoga', tags: ['toe-touch'],
    text: "Legs long in front, sit up on the sit bones, hinge from the hips and walk the hands down the legs. Bend the knees to keep the spine long." },
  { id: 'butterfly', name: 'Butterfly', kind: 'yoga', tags: ['mobility'],
    text: "Soles of the feet together, knees wide. Hold the ankles and fold forward from the hips as the knees soften toward the floor." },
  { id: 'supine_ham', name: 'Supine Hamstring Stretch', kind: 'yoga', tags: ['toe-touch'],
    text: "On the back, loop a towel or belt around one foot and lift that leg toward straight. Other leg stays long on the floor. Flex the lifted foot.",
    swap: "No strap? A towel, a scarf, or hands behind the thigh all work." },
  { id: 'straddle_fold', name: 'Wide Straddle Fold', kind: 'yoga', tags: ['toe-touch'],
    text: "Seated, legs wide, toes up. Walk the hands forward between the legs, hinging from the hips. Stop where the low back still feels long." },
  { id: 'supine_twist', name: 'Supine Twist', kind: 'yoga', tags: ['recovery', 'mobility'],
    text: "On the back, draw one knee in and guide it across the body. Arms wide, gaze the opposite way. Let gravity do all of it." },
  { id: 'figure4_supine', name: 'Supine Figure 4', kind: 'yoga', tags: ['mobility', 'recovery'],
    text: "On the back, cross one ankle over the opposite knee and draw the bottom thigh toward the chest. Head and shoulders stay heavy." },
  { id: 'happy_baby', name: 'Happy Baby', kind: 'yoga', tags: ['recovery', 'mobility'],
    text: "On the back, knees wide toward the ribs, hold the outer feet or shins with the shins vertical. Rock gently if it feels good." },
  { id: 'knees_chest', name: 'Knees to Chest', kind: 'yoga', tags: ['recovery'],
    text: "Hug both knees in, low back pressing into the floor. Long exhale on every squeeze." },
  { id: 'rest', name: 'Quiet Rest', kind: 'yoga', tags: ['recovery'],
    text: "Lie flat, arms a little away from the body, palms up. Nothing to do. Let the breath return to its own rhythm.",
    cue: "The last pose is the one the body keeps." },
  { id: 'neck_side', name: 'Neck Side Stretch', kind: 'yoga', tags: ['mobility', 'recovery'],
    text: "Sit or stand tall, drop one ear toward the shoulder and rest the same-side hand lightly on the head. Opposite shoulder slides down." },
  { id: 'shoulder_rolls', name: 'Shoulder Rolls', kind: 'yoga', tags: ['mobility'],
    text: "Lift the shoulders toward the ears, roll them back and down. Big, slow circles — five back, five forward." },
  { id: 'wall_chest', name: 'Wall Chest Opener', kind: 'yoga', tags: ['mobility', 'pull-up'],
    text: "Forearm flat on a wall or doorframe at shoulder height, then turn the chest away from that arm until the front of the shoulder opens.",
    swap: "No wall? Clasp the hands behind the back and lift." },
  { id: 'wrist_circles', name: 'Wrist Circles & Flexor Stretch', kind: 'yoga', tags: ['mobility'],
    text: "Circle the wrists both ways, then extend one arm, palm up, and gently draw the fingers back with the other hand. Switch." },
  { id: 'standing_backbend', name: 'Gentle Standing Backbend', kind: 'yoga', tags: ['mobility'],
    text: "Hands to the low back, elbows drawing together, lift the chest and lean back a few degrees. Length first, bend second." },

  // ——— Calisthenics ———
  { id: 'squat', name: 'Bodyweight Squat', kind: 'calisthenics', tags: ['strength'],
    text: "Feet shoulder-width, toes slightly out. Sit the hips back and down, knees tracking over the toes, chest tall. Drive through the whole foot to stand.",
    cue: "Depth you can control beats depth you fall into.",
    swap: "Tight ankles? Squat to a chair, or raise the heels on a book." },
  { id: 'pushup', name: 'Push-Up', kind: 'calisthenics', tags: ['strength'],
    text: "Hands slightly wider than the shoulders, body in one line. Lower until the chest is a fist from the floor, elbows at about 45 degrees, then press away.",
    cue: "Squeeze the glutes — the plank never leaves.",
    swap: "Hands on a table or wall, or knees down, keeps every rep honest." },
  { id: 'incline_pushup', name: 'Incline Push-Up', kind: 'calisthenics', tags: ['strength'],
    text: "Hands on a table, counter, or bench. Same line, same elbow path — the higher the hands, the lighter the load." },
  { id: 'knee_pushup', name: 'Knee Push-Up', kind: 'calisthenics', tags: ['strength'],
    text: "Knees down, ankles crossed, hips forward so the line runs crown to knees. Lower the chest, not the head." },
  { id: 'pike_pushup', name: 'Pike Push-Up', kind: 'calisthenics', tags: ['strength'],
    text: "Hips high in an inverted V, hands shoulder-width. Bend the elbows to lower the crown toward the floor between the hands, then press up." },
  { id: 'reverse_lunge', name: 'Reverse Lunge', kind: 'calisthenics', tags: ['strength'],
    text: "Step one foot back and lower until both knees are near 90 degrees. Torso upright. Push through the front heel to return.",
    cue: "Stepping back is kinder to the knees than stepping forward." },
  { id: 'split_squat', name: 'Split Squat', kind: 'calisthenics', tags: ['strength'],
    text: "Stagger the feet a stride apart and lower straight down until the back knee kisses the floor. All reps on one side, then switch." },
  { id: 'plank_hold', name: 'Forearm Plank', kind: 'calisthenics', tags: ['strength'],
    text: "Elbows under the shoulders, forearms parallel, hips level with the shoulders. Brace as if bracing for a light punch." },
  { id: 'side_plank', name: 'Side Plank', kind: 'calisthenics', tags: ['strength'],
    text: "On one forearm, feet stacked or staggered, hips lifted in a straight line. Top hand to the hip or the ceiling.",
    swap: "Drop the bottom knee to shorten the lever." },
  { id: 'shoulder_taps', name: 'Plank Shoulder Taps', kind: 'calisthenics', tags: ['strength'],
    text: "From a high plank with the feet wide, lift one hand and tap the opposite shoulder. Alternate slowly and keep the hips from rocking." },
  { id: 'glute_bridge', name: 'Glute Bridge', kind: 'calisthenics', tags: ['strength', 'mobility'],
    text: "On the back, knees bent, feet flat and hip-width. Press through the heels and lift the hips until the body is one line from knee to shoulder. Squeeze at the top." },
  { id: 'single_leg_bridge', name: 'Single-Leg Bridge', kind: 'calisthenics', tags: ['strength'],
    text: "Bridge with one foot on the floor and the other knee drawn in. Keep the hips level as you lift; lower slowly." },
  { id: 'hollow_hold', name: 'Hollow Hold', kind: 'calisthenics', tags: ['strength'],
    text: "On the back, low back pressed flat, then lift the shoulders and legs a few inches off the floor. Arms overhead or by the hips.",
    cue: "If the low back lifts, raise the legs higher — the floor should never see daylight.",
    swap: "Tuck the knees to shorten the body until the back stays flat." },
  { id: 'superman', name: 'Superman Pulls', kind: 'calisthenics', tags: ['pull-up', 'strength'],
    text: "Face down, arms reaching forward. Lift the chest and legs, then pull the elbows back toward the ribs and squeeze the shoulder blades before reaching forward again.",
    cue: "The closest thing to a pull-up with nothing but a floor." },
  { id: 'dead_hang', name: 'Dead Hang', kind: 'calisthenics', tags: ['pull-up'],
    text: "Hang from a bar with a full grip, shoulders relaxed but not collapsed, legs long. Breathe and let the grip build.",
    swap: "No bar? Hang from a sturdy doorframe edge, or hold a loaded towel row isometric." },
  { id: 'scap_pull', name: 'Scapular Pulls', kind: 'calisthenics', tags: ['pull-up'],
    text: "From a dead hang with straight arms, pull the shoulder blades down and together to lift the body an inch or two. Pause, then release with control.",
    cue: "This is where the pull-up actually starts." },
  { id: 'negative_pullup', name: 'Slow Negative Pull-Up', kind: 'calisthenics', tags: ['pull-up', 'strength'],
    text: "Jump or step to the top position, chin over the bar, then lower as slowly as you can — aim for 5 seconds. Step back up and repeat.",
    cue: "Negatives buy the pull-up before you can do one." },
  { id: 'pullup', name: 'Pull-Up', kind: 'calisthenics', tags: ['pull-up', 'strength'],
    text: "From a dead hang, set the shoulder blades down, then pull the chest toward the bar with the elbows driving to the ribs. Lower all the way.",
    swap: "Not yet? Negatives and towel rows are the same movement at a lighter weight." },
  { id: 'chinup', name: 'Chin-Up', kind: 'calisthenics', tags: ['pull-up', 'strength'],
    text: "Palms facing you, hands shoulder-width. Pull until the chin clears the bar, keeping the ribs down. Often the first one to arrive." },
  { id: 'towel_row', name: 'Towel Rows on a Door', kind: 'calisthenics', tags: ['pull-up', 'strength'],
    text: "Loop a towel around a securely latched door handle (hinge side, door open). Hold both ends, walk the feet in, lean back with straight arms and row the chest toward the handle.",
    cue: "The further the feet, the heavier the row." },
  { id: 'inverted_row', name: 'Desk / Table Inverted Row', kind: 'calisthenics', tags: ['pull-up', 'strength'],
    text: "Lie under a sturdy table, grip the edge, body straight, and pull the chest to the underside. Bend the knees to make it lighter.",
    swap: "No safe table? Towel rows on a door." },
  { id: 'ytw', name: 'Y-T-W Raises', kind: 'calisthenics', tags: ['pull-up', 'mobility'],
    text: "Face down, forehead resting. Lift the arms into a Y, then a T, then a W with the elbows pulling down. Three slow shapes, one rep." },
  { id: 'hanging_knee_raise', name: 'Hanging Knee Raise', kind: 'calisthenics', tags: ['pull-up', 'strength'],
    text: "From a dead hang, draw both knees toward the chest without swinging. Lower slowly and resist the swing.",
    swap: "No bar? Hollow hold with a knee tuck." },
  { id: 'wall_sit', name: 'Wall Sit', kind: 'calisthenics', tags: ['strength'],
    text: "Back flat to a wall, slide down until the knees are near 90 degrees. Weight in the heels, breathe steadily." },
  { id: 'chair_dip', name: 'Chair Dip', kind: 'calisthenics', tags: ['strength'],
    text: "Hands on the edge of a stable chair behind you, feet forward. Bend the elbows straight back and lower the hips, then press up.",
    swap: "Bend the knees and bring the feet in to lighten it." },
];

// step: [moveId, seconds, side?, reps?]
const s = (id, sec, side, reps) => ({ id, sec, side: side || '', reps: reps || '' });

const ROUTINES = [
  {
    id: 'daily_flow', name: 'Daily Flow', mins: 28, credit: 'Sequence by Emma', checkin: true,
    note: 'The long one. Breath, ground, stand, balance, rest.',
    steps: [
      s('childs_pose', 90), s('cat_cow', 60), s('tabletop_ext', 60), s('low_lunge_opener', 45, 'Right side'), s('low_lunge_opener', 45, 'Left side'),
      s('down_dog', 45), s('walk_up', 20), s('halfway_lift', 15), s('forward_fold', 30), s('mountain', 20), s('plank', 30), s('chaturanga', 20), s('cobra', 30), s('down_dog', 45),
      s('runners_lunge', 45, 'Right side'), s('half_splits', 45, 'Right side'), s('knee_to_nose', 30, 'Right side'),
      s('runners_lunge', 45, 'Left side'), s('half_splits', 45, 'Left side'), s('knee_to_nose', 30, 'Left side'),
      s('warrior2', 45, 'Right side'), s('side_angle', 40, 'Right side'), s('reverse_warrior', 30, 'Right side'), s('triangle', 45, 'Right side'), s('reverse_triangle', 45, 'Right side'),
      s('warrior2', 45, 'Left side'), s('side_angle', 40, 'Left side'), s('reverse_warrior', 30, 'Left side'), s('triangle', 45, 'Left side'), s('reverse_triangle', 45, 'Left side'),
      s('star', 30), s('wide_leg_fold', 60),
      s('standing_split', 45, 'Right side'), s('knee_raise', 20, 'Right side'), s('figure4_standing', 40, 'Right side'), s('warrior3', 30, 'Right side'), s('standing_split', 30, 'Right side'),
      s('standing_split', 45, 'Left side'), s('knee_raise', 20, 'Left side'), s('figure4_standing', 40, 'Left side'), s('warrior3', 30, 'Left side'), s('standing_split', 30, 'Left side'),
      s('forward_fold', 60), s('childs_pose', 90),
    ],
  },
  {
    id: 'quick_stretch', name: 'Quick Stretch', mins: 5, checkin: true,
    note: 'Five minutes, ending in the daily toe-touch rep.',
    steps: [s('childs_pose', 45), s('cat_cow', 45), s('down_dog', 45), s('half_splits', 45, 'Right side'), s('half_splits', 45, 'Left side'), s('forward_fold', 75)],
  },
  {
    id: 'morning', name: 'Morning Wake-Up', mins: 8, checkin: false,
    note: 'Gentle joint mobilisation before the day starts asking.',
    steps: [s('neck_rolls', 45), s('cat_cow', 60), s('thread_needle', 45, 'Right side'), s('thread_needle', 45, 'Left side'), s('down_dog', 45),
      s('low_lunge_reach', 45, 'Right side'), s('low_lunge_reach', 45, 'Left side'), s('forward_fold', 45), s('standing_side_bend', 40, 'Right side'), s('standing_side_bend', 40, 'Left side')],
  },
  {
    id: 'hips_hams', name: 'Hips & Hamstrings', mins: 15, checkin: true,
    note: 'The toe-touch deep dive. Long holds, 60–90 seconds.',
    steps: [s('down_dog', 60), s('ragdoll', 75), s('half_splits', 75, 'Right side'), s('half_splits', 75, 'Left side'), s('lizard', 75, 'Right side'), s('lizard', 75, 'Left side'),
      s('pyramid', 60, 'Right side'), s('pyramid', 60, 'Left side'), s('seated_fold', 90), s('butterfly', 75), s('supine_ham', 75, 'Right side'), s('supine_ham', 75, 'Left side'), s('straddle_fold', 90)],
  },
  {
    id: 'strength', name: 'Full-Body Strength', mins: 15, checkin: false, rounds: 3,
    note: 'Zero equipment. Two to three rounds — stop when form goes.',
    steps: [s('squat', 45, '', '12 reps'), s('pushup', 45, '', '8–12 reps'), s('reverse_lunge', 50, '', '8 each side'), s('shoulder_taps', 40, '', '10 each side'),
      s('glute_bridge', 40, '', '15 reps'), s('hollow_hold', 30), s('superman', 40, '', '10 reps')],
  },
  {
    id: 'pullup_home', name: 'Pull-up Work — Home', mins: 10, checkin: false,
    note: 'Bar required. Quality over quantity; rest fully.',
    steps: [s('dead_hang', 30), s('scap_pull', 40, '', '6 reps'), s('rest', 45), s('negative_pullup', 45, '', '3 reps'), s('rest', 60),
      s('negative_pullup', 45, '', '3 reps'), s('rest', 60), s('dead_hang', 40), s('hanging_knee_raise', 40, '', '8 reps')],
  },
  {
    id: 'pullup_travel', name: 'Pull-up Work — Traveling', mins: 10, checkin: false,
    note: 'No bar, no gym. A door and a table are enough.',
    steps: [s('towel_row', 45, '', '10 reps'), s('rest', 30), s('inverted_row', 45, '', '8 reps'), s('rest', 30),
      s('superman', 40, '', '10 reps'), s('ytw', 45, '', '5 rounds'), s('towel_row', 45, '', '10 reps'), s('wall_chest', 40, 'Right side'), s('wall_chest', 40, 'Left side')],
  },
  {
    id: 'evening', name: 'Evening Wind-Down', mins: 10, checkin: false, breath: { cycle: 10, inhale: 4 },
    note: 'Floor-based and quiet. Breath pacing: 4 in, 6 out.',
    steps: [s('childs_pose', 90), s('supine_twist', 75, 'Right side'), s('supine_twist', 75, 'Left side'), s('figure4_supine', 60, 'Right side'), s('figure4_supine', 60, 'Left side'),
      s('happy_baby', 60), s('knees_chest', 45), s('rest', 120)],
  },
  {
    id: 'desk', name: 'Desk Reset', mins: 3, checkin: false,
    note: 'Standing, no mat, shoes on. Three minutes between meetings.',
    steps: [s('neck_side', 30, 'Right side'), s('neck_side', 30, 'Left side'), s('shoulder_rolls', 30), s('wall_chest', 30, 'Right side'), s('wall_chest', 30, 'Left side'),
      s('wrist_circles', 30), s('forward_fold', 40), s('standing_backbend', 25)],
  },
];

const THOUGHTS = [
  'What would today look like if it were easy?',
  'Nothing here is a test.',
  'The body keeps the practice, not the record.',
  'The pose you avoid is the one with the most to say.',
  'Slower than you think you should go.',
  'You are allowed to stop early.',
  'Notice what is different from yesterday.',
  'Breath first. The pose is optional.',
];

const CHECKIN_LEVELS = [
  { id: 'knees', label: 'Knees', reply: 'Knees today, shins soon. The fold is a conversation, not a verdict.' },
  { id: 'shins', label: 'Shins', reply: 'Shins. The floor is getting closer every week you show up.' },
  { id: 'ankles', label: 'Ankles', reply: 'Ankles — the toes are officially within reach.' },
  { id: 'toes', label: 'Toes', reply: 'Toes. That was the whole goal once. Keep going, gently.' },
  { id: 'palms', label: 'Flat palms', reply: 'Flat palms. Time to find something new that is out of reach.' },
];

// Move ids that have a generated illustration at images/<id>.png — add ids here as images land.
const IMAGES = [
  'butterfly',
  'cat_cow',
  'chair_dip',
  'chaturanga',
  'childs_pose',
  'chinup',
  'cobra',
  'dead_hang',
  'down_dog',
  'forward_fold',
  'glute_bridge',
  'halfway_lift',
  'hanging_knee_raise',
  'happy_baby',
  'hollow_hold',
  'incline_pushup',
  'inverted_row',
  'knee_pushup',
  'knee_raise',
  'knee_to_nose',
  'mountain',
  'neck_rolls',
  'negative_pullup',
  'pike_pushup',
  'plank',
  'pullup',
  'pushup',
  'reverse_lunge',
  'scap_pull',
  'seated_fold',
  'shoulder_rolls',
  'shoulder_taps',
  'side_plank',
  'single_leg_bridge',
  'split_squat',
  'squat',
  'superman',
  'supine_twist',
  'tabletop_ext',
  'towel_row',
  'triangle',
  'walk_up',
  'wall_sit',
  'warrior2',
  'wrist_circles',
  'ytw',
];
window.REACH_DATA = { MOVES, ROUTINES, THOUGHTS, CHECKIN_LEVELS, IMAGES };
